name: Run Tests and Collect Code Coverage

on:
  push:
    branches: [ master-dev ]
  pull_request:
    branches: [ master-dev ]
  workflow_dispatch:  # umožní ruční spuštění

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Run tests with coverage
      run: |
        dotnet test STIN_News_Module \
          --no-build \
          /p:CollectCoverage=true \
          /p:CoverletOutput=TestResults/coverage.xml \
          /p:CoverletOutputFormat=opencover

    - name: Install ReportGenerator
      run: dotnet tool install --global dotnet-reportgenerator-globaltool

    - name: Generate coverage report
      run: |
        reportgenerator \
          -reports:STIN_News_Module/TestResults/coverage.xml \
          -targetdir:coveragereport \
          -reporttypes:Html

    - name: Upload coverage report as artifact
      uses: actions/upload-artifact@v4
      with:
        name: code-coverage-report
        path: coveragereport
